# Generated by Django 4.2.1 on 2023-05-19 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("AR", "Arena para gatos"),
                    ("JU", "Juguetes para gatos"),
                    ("CO", "Comida para gatos"),
                    ("AC", "Accesorios para gatos"),
                ],
                max_length=2,
            ),
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("locality", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=50)),
                ("mobile", models.IntegerField(default=0)),
                ("zipcode", models.IntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("Lima", "Lima"),
                            ("Áncon", "Áncon"),
                            ("Ate", "Ate"),
                            ("Barranco", "Barranco"),
                            ("Breña", "Breña"),
                            ("Carabayllo", "Carabayllo"),
                            ("Chaclacayo", "Chaclacayo"),
                            ("Chorrillos", "Chorrillos"),
                            ("Cieneguilla", "Cieneguilla"),
                            ("Comas", "Comas"),
                            ("El Agustino", "El Agustino"),
                            ("Independencia", "Independencia"),
                            ("Jesús María", "Jesús María"),
                            ("La Molina", "La Molina"),
                            ("La Victoria", "La Victoria"),
                            ("Lince", "Lince"),
                            ("Los Olivos", "Los Olivos"),
                            ("Lurigancho", "Lurigancho"),
                            ("Lurín", "Lurín"),
                            ("Magdalena del Mar", "Magdalena del Mar"),
                            ("Miraflores", "Miraflores"),
                            ("Pachacamac", "Pachacamac"),
                            ("Pucusana", "Pucusana"),
                            ("Pueblo Libre", "Pueblo Libre"),
                            ("Puente Piedra", "Puente Piedra"),
                            ("Punta Hermosa", "Punta Hermosa"),
                            ("Punta Negra", "Punta Negra"),
                            ("Rímac", "Rímac"),
                            ("San Bartolo", "San Bartolo"),
                            ("San Borja", "San Borja"),
                            ("San Isidro", "San Isidro"),
                            ("San Juan de Lurigancho", "San Juan de Lurigancho"),
                            ("San Juan de Miraflores", "San Juan de Miraflores"),
                            ("San Luis", "San Luis"),
                            ("San Martín de Porres", "San Martín de Porres"),
                            ("San Miguel", "San Miguel"),
                            ("Santa Anita", "Santa Anita"),
                            ("Santa María del Mar", "Santa María del Mar"),
                            ("Santa Rosa", "Santa Rosa"),
                            ("Santiago de Surco", "Santiago de Surco"),
                            ("Surquillo", "Surquillo"),
                            ("Villa El Salvador", "Villa El Salvador"),
                            ("Villa María del Triunfo", "Villa María del Triunfo"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
